- name: Disable password saving in Chromium and Firefox
  hosts: all
  become: true
  vars:
    chromium_policy_path: /etc/chromium/policies/managed
    firefox_policy_path: /etc/firefox/policies

  tasks:
    - name: Ensure Chromium policy directory exists
      file:
        path: "{{ chromium_policy_path }}"
        state: directory
        mode: '0755'

    - name: Deploy Chromium password policy
      copy:
        dest: "{{ chromium_policy_path }}/disable-password-manager.json"
        content: |
          {
            "PasswordManagerEnabled": false,
            "CredentialsEnableService": false
          }
        mode: '0644'

    - name: Ensure Firefox policy directory exists
      file:
        path: "{{ firefox_policy_path }}"
        state: directory
        mode: '0755'

    - name: Deploy Firefox password policy
      copy:
        dest: "{{ firefox_policy_path }}/policies.json"
        content: |
          {
            "policies": {
              "PasswordManagerEnabled": false
            }
          }
        mode: '0644'
