- hosts: all
  gather_facts: false
  become: true
  tasks:
  - name: Copy repo file to host
    copy:
      dest: /etc/yum.repos.d/
      mode: '0644'
      src: /home/semaphore/playbooks/repo/1C.repo
      
  - name: Install 1c-enterprise-client
    dnf:
      name: 1c-enterprise-8.3.24.1586-client
      state: present
      disable_gpg_check: true
      
  - name: Rename files
    command: mv {{ item.src }} {{ item.dest }}
    args:
      removes: "{{ item.src }}"
    with_items:
      - { src: '/opt/1cv8/common/libstdc++.so.6', dest: '/opt/1cv8/common/libstdc++.so.6.old' }
      - { src: '/opt/1cv8/x86_64/8.3.24.1586/libstdc++.so.6', dest: '/opt/1cv8/x86_64/8.3.24.1586/libstdc++.so.6.old' }

  - name: Create links
    file:
      src: "{{ item.src }}"
      dest: "{{ item.dest }}"
      state: link
    with_items:
      - { src: '/usr/lib/x86_64-linux-gnu/libstdc++.so.6', dest: '/opt/1cv8/common/libstdc++.so.6' }
      - { src: '/usr/lib/x86_64-linux-gnu/libstdc++.so.6', dest: '/opt/1cv8/x86_64/8.3.24.1586/libstdc++.so.6' }

  - name: Find user directories ending with dgp.gazprom.ru
    find:
      paths: /home
      recurse: no
      patterns: "*dgp.gazprom.ru"
      file_type: directory
    register: user_dirs

  - name: Create directories in user profile
    file:
      path: "{{ item.path }}/.1C/1cestart"
      state: directory
      mode: '0755'
    loop: "{{ user_dirs.files }}"
    when: user_dirs.matched > 0

  - name: Copy base file to host
    copy:
      src: /home/semaphore/playbooks/other/ibases.v8i
      dest: "{{ item.path }}/.1C/1cestart/ibases.v8i"
      mode: '0777'
    loop: "{{ user_dirs.files }}"
    when: user_dirs.matched > 0

  - name: Copy link file to desktop
    copy:
      src: "/home/semaphore/playbooks/other/1С Предприятие.desktop"
      dest: "{{ item.path }}/Рабочий стол/1С Предприятие.desktop"
      owner: '{{ item.path | basename | regex_replace("@dgp\.gazprom\.ru", "") }}'
      group: "Domain Users"	  
      mode: '0755'
    loop: "{{ user_dirs.files }}"
    when: user_dirs.matched > 0