- gather_facts: false
  hosts: all
  tasks:
#  - name: /etc/pam.d/su
#    replace:
#      path: /etc/pam.d/su
#      regexp: '^#(.*pam_wheel\.so\s+use_uid.*)$'
#      replace: '\1'
      
  - name: /etc/sysctl.conf
#    blockinfile:
#      path: /etc/sysctl.conf
#      block: |
#        kernel.dmesg_restrict=1
#        kernel.kptr_restrict=2
#        net.core.bpf_jit_harden=2
#        kernel.perf_event_paranoid=3
#        kernel.kexec_load_disabled=1
#        user.max_user_namespaces=0
#        kernel.unprivileged_bpf_disabled=1
#        vm.unprivileged_userfaultfd=0
#        dev.tty.ldisc_autoload=0
#        vm.mmap_min_addr=4096
#        kernel.randomize_va_space=2
#        kernel.yama.ptrace_scope=3
#        fs.protected_symlinks=1
#        fs.protected_hardlinks=1
#        fs.protected_fifos=2
#        fs.protected_regular=2
#        fs.suid_dumpable=0
    copy:
      dest: /etc/sysctl.conf
      mode: '0644'
      src: /home/semaphore/playbooks/conf/sysctl.conf
      
  - name: Add parameters to GRUB_CMDLINE_LINUX if not already present
    shell: |
      if ! grep -q 'init_on_alloc=1 slab_nomerge iommu=force iommu.strict=1 iommu.passthrough=0 randomize_kstack_offset=1 mitigations=auto,nosmt vsyscall=none debugfs=no-mount tsx=off' /etc/default/grub; then
        sed -i '/^GRUB_CMDLINE_LINUX="/ s/"$/ init_on_alloc=1 slab_nomerge iommu=force iommu.strict=1 iommu.passthrough=0 randomize_kstack_offset=1 mitigations=auto,nosmt vsyscall=none debugfs=no-mount tsx=off"/' /etc/default/grub
        grub2-mkconfig -o /boot/grub2/grub.cfg
      fi
    args:
      executable: /bin/bash